name: chat_poc_one
description: "A Get Stream Chat integration proof of concept"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

  # -------- PACKAGES -------------#

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #  CAUTION !! Don't change versions of connectivity plus and stream chat flutter !!
#  stream_chat_flutter: 7.2.0-hotfix.1
  stream_chat_flutter_core: ^7.2.0
  connectivity_plus: 5.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  faker: ^2.1.0
  jiffy: ^6.3.0
  meta: ^1.11.0
  logger: ^2.2.0
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700